[Variables]
CenterColor=		(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureAudioRMSskull]),	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureAudioRMSskull]),	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureAudioRMSskull]),(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureAudioRMSskull])
InnerColor=			(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureAudioRMS]),	 	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureAudioRMS]),	 	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureAudioRMS])     ,(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureAudioRMS])	 
MiddleSolidColor=	(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureAudioRMS1]),	 	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureAudioRMS1]),	 	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureAudioRMS1])	   ,(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureAudioRMS1])	 
MiddleColor=		(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureAudioRMS2]),	 	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureAudioRMS2]),	 	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureAudioRMS2])	   ,(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureAudioRMS2])	 
OuterColor=			(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureAudioRMS3]),	 	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureAudioRMS3]),	 	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureAudioRMS3])	   ,(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureAudioRMS3]) 

ScrollMouseIncrement=0.1
