[Variables]
CenterColor=		(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureBand1]),	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureBand1]),	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureBand1]),(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureBand1])
InnerColor=			(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureBand2]),	 	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureBand2]),	 	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureBand2])     ,(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureBand2])	 
MiddleSolidColor=	(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureBand3]),	 	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureBand3]),	 	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureBand3])	   ,(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureBand3])	 
MiddleColor=		(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureBand4]),	 	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureBand4]),	 	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureBand4])	   ,(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureBand4])	 
OuterColor=			(#DefaultRED# - (#DefaultRED# - #RED#) * [MeasureBand5]),	 	(#DefaultGREEN# - (#DefaultGREEN# - #GREEN#) * [MeasureBand5]),	 	(#DefaultBLUE# - (#DefaultBLUE# - #BLUE#) * [MeasureBand5])	   ,(#DefaultALPHA# - (#DefaultALPHA# - #ALPHA#) * [MeasureBand5]) 

ScrollMouseIncrement=0.1
