[JitterX0]
Measure=Calc
Formula=((JXR0 * MeasureBand0 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterX1]
Measure=Calc
Formula=((JXR1 * MeasureBand1 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterX2]
Measure=Calc
Formula=((JXR2 * MeasureBand2 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterX3]
Measure=Calc
Formula=((JXR3 * MeasureBand3 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterX4]
Measure=Calc
Formula=((JXR4 * MeasureBand4 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterX5]
Measure=Calc
Formula=((JXR5 * MeasureBand5 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#