[JitterY0]
Measure=Calc
Formula=((JYR0 * MeasureBand0 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterY1]
Measure=Calc
Formula=((JYR1 * MeasureBand1 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterY2]
Measure=Calc
Formula=((JYR2 * MeasureBand2 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterY3]
Measure=Calc
Formula=((JYR3 * MeasureBand3 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterY4]
Measure=Calc
Formula=((JYR4 * MeasureBand4 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
[JitterY5]
Measure=Calc
Formula=((JYR5 * MeasureBand5 * Random))
HighBound=#MaxRingJitter#
UpdateRandom=1
UpdateDivider=#JitterSpeed#