[JXR0]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JXR1]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JXR2]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JXR3]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JXR4]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JXR5]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#