[JYR0]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JYR1]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JYR2]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JYR3]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JYR4]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#
[JYR5]
Measure=Calc
Formula=((Random = 1) ? 1 : -1)
HighBound=1
UpdateRandom=1
UpdateDivider=#JitterDirectionSpeed#