[JitterX0]
Measure=Calc
Formula=((JXR0 * MeasureBand0 * Random) * #Scale#)
HighBound=#MaxJitter0#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
DynamicVariables=1
Group=Scale
[JitterX1]
Measure=Calc
Formula=((JXR1 * MeasureBand1 * Random) * #Scale#)
HighBound=#MaxJitter1#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
DynamicVariables=1
Group=Scale
[JitterX2]
Measure=Calc
Formula=((JXR2 * MeasureBand2 * Random) * #Scale#)
HighBound=#MaxJitter2#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
DynamicVariables=1
Group=Scale
[JitterX3]
Measure=Calc
Formula=((JXR3 * MeasureBand3 * Random) * #Scale#)
HighBound=#MaxJitter3#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
DynamicVariables=1
Group=Scale
[JitterX4]
Measure=Calc
Formula=((JXR4 * MeasureBand4 * Random) * #Scale#)
HighBound=#MaxJitter4#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
DynamicVariables=1
Group=Scale
[JitterX5]
Measure=Calc
Formula=((JXR5 * MeasureBand5 * Random) * #Scale#)
HighBound=#MaxJitter5#
UpdateRandom=1
UpdateDivider=#JitterSpeed#
DynamicVariables=1
Group=Scale